# FROM almalinux:9
# ARG name="chaitanya" \
#     technology="Devops" \
#     environment="Production"
# RUN echo "name: $name  , technology: $technology , environment:$environment"
# CMD ["sleep","100"]
ARG version
FROM almalinux:${version}
ARG name="chaitanya" \
    technology="Devops" \
    environment="Production"
RUN echo "name: $name  , technology: $technology , environment:$environment"
CMD ["sleep","100"]